TELEGRAM_USER_ID_LIST = []
SEND_TELEGRAM_MESSAGE = True
TELEGRAM_API_KEY = ""

SYMBOL = "MINAUSDT"
BINANCE_API_KEY = ""
BINANCE_SECRET_KEY = ""
MAXIMUM_NUMBER_OF_API_CALL_TRIES = 5
BINANCE_API_TIMEOUT = 60

VOLATILITY_THRESHOLD = 2
RSI_THRESHOLD = 70
